DECLARE
EMP_ID NUMBER:=101;
EMP_NAME VARCHAR(20):='THOMAS';
EMP_SALARY NUMBER:=25000;

BEGIN
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE ID: '||EMP_ID);
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME: '||EMP_NAME);
    DBMS_OUTPUT.PUT_LINE('SALARY: RS. '||EMP_SALARY);
    DBMS_OUTPUT.PUT_LINE('HOUSE RENT ALLOWANCE: RS. '||(0.40*EMP_SALARY));
    IF EMP_SALARY > 60000 THEN
    DBMS_OUTPUT.PUT_LINE('YOU NEED TO PAY TAX');
    ELSE
    DBMS_OUTPUT.PUT_LINE('YOU DO NOT HAVE TO PAY TAX'); 
    END IF;
END;
